# Site settings
title: BitForge
header-img: img/home-bg.jpg
email: contact@bitforge.com.br
copyright_name: BitForge Tecnologia
description: "Especialistas em software prestando consultoria em dezenas de empresas de diferentes indústrias ou serviços."
baseurl: ""
url: "http://bitforgebr.github.io"
twitter_username: bitforgebr
github_username:  bitforgebr
facebook_username:  bitforge
email_username: contact@bitforge.com.br

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

defaults:
  -
    values:
      layout: post

