# Site settings
title: BitForge
header-img: img/home-bg.jpg
email: contact@bitforge.com.br
copyright_name: BitForge Tecnologia
description: "Especialistas em software prestando consultoria em dezenas de empresas de diferentes indústrias ou serviços."
baseurl: "http://bitforgebr.github.io"
url: "http://bitforgebr.github.io"
twitter_username: bitforgebr
github_username:  bitforgebr
facebook_username:  bitforge
email_username: contact@bitforge.com.br

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

defaults:
  -
    scope:
      path: "_posts/pt"
    values:
      layout: post
      lang: en

